### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by avichalp** [luciodale/arco#1]
Hey! 

Thanks for `arco`. It is an interesting library.

It seems like a dependency is missing when I try to download from maven (using Clojure cli/deps.edn). However, when I try to download from git `tick` get downloaded and is available on `classpath`.

```
Syntax error (FileNotFoundException) compiling at (utils.cljc:1:1).
Could not locate tick/alpha/api__init.class, tick/alpha/api.clj or tick/alpha/api.cljc on classpath.
```
I checked the pom file, the dependency is missing there too. Also, dependencies are not shown on Clojars page.

**Comment by luciodale** [comment]
Thanks for flagging! Will
Fix soon

**Comment by luciodale** [comment]
Added dependency ;)!  I forgot to add tick to `project.clj`. Fixed now.
